### ISSUE TITLE
Callouts in code not handled

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/rfd-site#62]
### Source

```
[,oxql]
----
get sled_data_link:bytes_sent <1>
   <2>
    | filter timestamp > @now() - 1m <3>
----
```

### Result

<img width="746" alt="image" src="https://github.com/user-attachments/assets/d89d8ce6-b5d9-42de-b9a8-f857b0215887">

### Probably relevant code

https://github.com/oxidecomputer/react-asciidoc/blob/fc45a5210954ae73f53210b5aef84bb62818a6f8/src/asciidoc/templates/Listing.tsx#L31-L43

**Comment by benjaminleonard** [comment]
Looks like it's broken by `hljs.highlight` – which runs after the substitutions are made and I'm guessing escapes any HTML in there.

**Comment by david-crespo** [comment]
time to switch to shiki

**Comment by benjaminleonard** [comment]
Well it's an issue with Shiki also, because it's fundamental to how they render the highlighted code.

I have a fix that requires regex...which makes me a tad uncomfortable but in this instance it's probably okay.

I'll show the fix using the new syntax renderer which isn't merged so the code will look different, but the concept is basically the same. Essentially we want to take the callouts, turn them into something identifiable, then replace them after the syntax highlighting is complete.

```ts
// Replace callouts with placeholders
const calloutRegex = /<b class="conum">\(\d+\)<\/b>/g
const callouts = []
let contentWithPlaceholders = literalBlock.content.replace(calloutRegex, (match) => {
  callouts.push(match)
  return `__CALL_OUT_${callouts.length - 1}__`
})

// Highlight the content with placeholders
const highlightedContent = await codeToHtml(contentWithPlaceholders, {
  lang: literalBlock.language,
  theme: theme,
  structure: 'inline',
})

// Replace placeholders with original callouts
const finalContent = highlightedContent.replace(
  /__CALL_OUT_(\d+)__/g,
  (_, index) => callouts[Number(index)],
)
```

We would need to enforce the conum rendering, since we don't want a custom document attribute like `icons` messing with the output.

**Comment by benjaminleonard** [comment]
Currently blocked by https://github.com/oxidecomputer/react-asciidoc/pull/24 – only because I don't want to implement this twice.

Tagging you since you had mentioned this issue – @bnaecker

**Comment by benjaminleonard** [comment]
In the end I added an interim implementation because I didn't want to rush the move to the new renderer.
